#ifndef GOCHYA_CORE_H
#define GOCHYA_CORE_H

#pragma once

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

enum GochyaStatus
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  GochyaStatus_Ok = 0,
  GochyaStatus_InvalidArgument = 1,
  GochyaStatus_BufferTooSmall = 2,
  GochyaStatus_SchemaMismatch = 3,
  GochyaStatus_DomainRejected = 4,
  GochyaStatus_InternalError = 255,
};
#if __STDC_VERSION__ >= 202311L
typedef enum GochyaStatus GochyaStatus;
#else
typedef int32_t GochyaStatus;
#endif // __STDC_VERSION__ >= 202311L

typedef struct GochyaPunchMetricsV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t technique_type;
  uint8_t combo_len;
  float peak_accel_mps2;
  float exec_time_seconds;
  float precision;
  float rhythm_score;
  uint8_t reserved[16];
} GochyaPunchMetricsV1;

typedef struct GochyaHeartEvidenceV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t reserved0[2];
  uint16_t baseline_bpm;
  uint16_t mean_bpm;
  float present;
  float confidence;
  int16_t delta_bpm;
  uint8_t reserved[14];
} GochyaHeartEvidenceV1;

typedef struct GochyaHeartVerdictV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t passed;
  uint8_t reason;
  float heart_score;
  uint8_t reserved[16];
} GochyaHeartVerdictV1;

typedef struct GochyaDailyActivityV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t workout_count;
  uint8_t reserved0;
  uint32_t steps;
  uint16_t sleep_minutes;
  uint16_t active_calories;
  uint8_t reserved[16];
} GochyaDailyActivityV1;

typedef struct GochyaDailyGoalsV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t reserved0[2];
  uint32_t steps;
  float sleep_hours;
  uint16_t active_calories;
  uint8_t reserved[14];
} GochyaDailyGoalsV1;

typedef struct GochyaTechniqueStatsV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t technique_type;
  uint8_t rarity;
  float base_damage;
  float speed;
  float crit_chance;
  uint16_t stamina_cost;
  uint8_t quality;
  uint8_t reserved0;
  uint8_t reserved[16];
} GochyaTechniqueStatsV1;

uint32_t gochya_abi_version(void);

GochyaStatus gochya_quality_score_v1(const struct GochyaPunchMetricsV1 *metrics,
                                     const struct GochyaHeartEvidenceV1 *heart,
                                     uint8_t *out_score);

GochyaStatus gochya_validate_heart_v1(const struct GochyaHeartEvidenceV1 *heart,
                                      struct GochyaHeartVerdictV1 *out_verdict);

GochyaStatus gochya_compute_vitality_v1(const struct GochyaDailyActivityV1 *activity,
                                        const struct GochyaDailyGoalsV1 *goals,
                                        uint32_t streak_days,
                                        uint16_t *out_vitality);

GochyaStatus gochya_derive_technique_v1(const struct GochyaPunchMetricsV1 *metrics,
                                        const struct GochyaHeartEvidenceV1 *heart,
                                        float tech_level,
                                        struct GochyaTechniqueStatsV1 *out_stats);

#endif  /* GOCHYA_CORE_H */
