#ifndef GOCHYA_CORE_H
#define GOCHYA_CORE_H

#pragma once

/* Generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

enum GochyaStatus
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  GochyaStatus_Ok = 0,
  GochyaStatus_InvalidArgument = 1,
  GochyaStatus_BufferTooSmall = 2,
  GochyaStatus_SchemaMismatch = 3,
  GochyaStatus_DomainRejected = 4,
  GochyaStatus_InternalError = 255,
};
#if __STDC_VERSION__ >= 202311L
typedef enum GochyaStatus GochyaStatus;
#else
typedef int32_t GochyaStatus;
#endif // __STDC_VERSION__ >= 202311L

typedef struct GochyaPunchMetricsV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t technique_type;
  uint8_t combo_len;
  float peak_accel_mps2;
  float exec_time_seconds;
  float precision;
  float rhythm_score;
  uint8_t reserved[16];
} GochyaPunchMetricsV1;

typedef struct GochyaHeartEvidenceV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t reserved0[2];
  uint16_t baseline_bpm;
  uint16_t mean_bpm;
  float present;
  float confidence;
  int16_t delta_bpm;
  uint8_t reserved[14];
} GochyaHeartEvidenceV1;

typedef struct GochyaHeartVerdictV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t passed;
  uint8_t reason;
  float heart_score;
  uint8_t reserved[16];
} GochyaHeartVerdictV1;

typedef struct GochyaDailyActivityV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t workout_count;
  uint8_t reserved0;
  uint32_t steps;
  uint16_t sleep_minutes;
  uint16_t active_calories;
  uint8_t reserved[16];
} GochyaDailyActivityV1;

typedef struct GochyaDailyGoalsV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t reserved0[2];
  uint32_t steps;
  float sleep_hours;
  uint16_t active_calories;
  uint8_t reserved[14];
} GochyaDailyGoalsV1;

typedef struct GochyaPersonalBaselineV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t reserved0[2];
  uint32_t steps_14d_average;
  float sleep_hours_14d_average;
  uint16_t active_calories_14d_average;
  uint8_t reserved[14];
} GochyaPersonalBaselineV1;

typedef struct GochyaWorkoutV1 {
  uint8_t kind;
  uint8_t reserved0;
  uint16_t duration_minutes;
  uint16_t calories;
  uint8_t reserved[2];
} GochyaWorkoutV1;

typedef struct GochyaActivityInputV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t reserved0[2];
  uint32_t steps;
  uint16_t sleep_minutes;
  uint16_t active_calories;
  uint8_t sleep_quality;
  uint8_t workout_count;
  uint8_t stress_level;
  uint8_t stand_hours;
  uint8_t source;
  uint8_t pet_element;
  uint8_t reserved1[2];
  uint16_t avg_hr;
  uint16_t hr_zone_high_minutes;
  uint16_t meditation_minutes;
  uint16_t floors;
  uint64_t timestamp;
  struct GochyaWorkoutV1 workouts[8];
  uint8_t reserved[16];
} GochyaActivityInputV1;

typedef struct GochyaActivityResultV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint16_t vitality;
  int16_t stat_str;
  int16_t stat_agi;
  int16_t stat_end;
  int16_t stat_foc;
  uint8_t reserved[16];
} GochyaActivityResultV1;

typedef struct GochyaTechniqueStatsV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t technique_type;
  uint8_t rarity;
  float base_damage;
  float speed;
  float crit_chance;
  uint16_t stamina_cost;
  uint8_t quality;
  uint8_t reserved0;
  uint8_t reserved[16];
} GochyaTechniqueStatsV1;

typedef struct GochyaCombatCardV1 {
  float base_damage;
  float speed;
  float crit_chance;
  float effect_value;
  uint16_t stamina_cost;
  uint8_t technique_type;
  uint8_t effect_kind;
} GochyaCombatCardV1;

typedef struct GochyaCombatLoadoutV1 {
  uint32_t stat_str;
  uint32_t stat_agi;
  uint32_t stat_end;
  uint32_t stat_foc;
  int16_t gear_str_bonus;
  int16_t gear_agi_bonus;
  int16_t gear_end_bonus;
  int16_t gear_foc_bonus;
  uint8_t element;
  uint8_t tech_affinity;
  uint8_t pet_mood;
  uint8_t signature_idx;
  struct GochyaCombatCardV1 cards[5];
  uint8_t reserved[16];
} GochyaCombatLoadoutV1;

typedef struct GochyaCombatMatchV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t mode;
  uint8_t reserved0;
  struct GochyaCombatLoadoutV1 loadout_a;
  struct GochyaCombatLoadoutV1 loadout_b;
  uint8_t reserved[16];
} GochyaCombatMatchV1;

typedef struct GochyaCombatRoundV1 {
  uint8_t card_a_idx;
  uint8_t card_b_idx;
  uint8_t effect_kind;
  uint8_t reserved0;
  uint16_t damage_a_to_b;
  uint16_t damage_b_to_a;
  float effect_value;
} GochyaCombatRoundV1;

typedef struct GochyaCombatResultV1 {
  uint32_t struct_size;
  uint16_t schema_version;
  uint8_t winner;
  uint8_t round_count;
  uint16_t final_hp_a;
  uint16_t final_hp_b;
  uint64_t seed;
  struct GochyaCombatRoundV1 rounds[20];
  uint8_t reserved[16];
} GochyaCombatResultV1;

uint32_t gochya_abi_version(void);

GochyaStatus gochya_quality_score_v1(const struct GochyaPunchMetricsV1 *metrics,
                                     const struct GochyaHeartEvidenceV1 *heart,
                                     uint8_t *out_score);

GochyaStatus gochya_validate_heart_v1(const struct GochyaHeartEvidenceV1 *heart,
                                      struct GochyaHeartVerdictV1 *out_verdict);

GochyaStatus gochya_compute_vitality_v1(const struct GochyaDailyActivityV1 *activity,
                                        const struct GochyaDailyGoalsV1 *goals,
                                        uint32_t streak_days,
                                        uint16_t *out_vitality);

GochyaStatus gochya_compute_goals_v1(const struct GochyaPersonalBaselineV1 *baseline,
                                     struct GochyaDailyGoalsV1 *out_goals);

GochyaStatus gochya_compute_activity_v1(const struct GochyaActivityInputV1 *activity,
                                        const struct GochyaDailyGoalsV1 *goals,
                                        uint32_t streak_days,
                                        struct GochyaActivityResultV1 *out_result);

GochyaStatus gochya_derive_technique_v1(const struct GochyaPunchMetricsV1 *metrics,
                                        const struct GochyaHeartEvidenceV1 *heart,
                                        float tech_level,
                                        struct GochyaTechniqueStatsV1 *out_stats);

GochyaStatus gochya_simulate_combat_v1(const struct GochyaCombatMatchV1 *match_,
                                       uint64_t seed,
                                       struct GochyaCombatResultV1 *out_result);

#endif  /* GOCHYA_CORE_H */
